# Generated by Django 4.1.3 on 2022-11-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0005_rename_trackitems_trackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeTracker.customer'),
        ),
    ]
