# Generated by Django 4.1.3 on 2022-11-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0006_money_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trackItem',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='expenditure',
            new_name='expense',
        ),
    ]
