# Generated by Django 4.1.3 on 2022-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0002_trackitems_alter_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitems',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
