# Generated by Django 4.1.3 on 2022-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0003_trackitems_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(null=True)),
                ('savings', models.FloatField(null=True)),
                ('expenditure', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trackitems',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='trackitems',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='trackitems',
            name='income',
        ),
        migrations.RemoveField(
            model_name='trackitems',
            name='savings',
        ),
    ]
