# Generated by Django 4.1.3 on 2022-11-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0004_money_remove_trackitems_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trackItems',
            new_name='trackItem',
        ),
    ]
