# Generated by Django 4.1.3 on 2022-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeTracker', '0009_alter_customer_date_created_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
    ]
